fix(version): correctly set falcoctl version at build time
Each time a falcoctl artifact (binary/OCI image) is created we make sure that the falcoctl binary
has the version fields set.

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

diff --git a/build/Dockerfile b/build/Dockerfile
--- a/build/Dockerfile
+++ b/build/Dockerfile
@@ -1,15 +1,33 @@
 FROM golang:1.19 as builder
 WORKDIR /tmp/builder
 
+ARG RELEASE
+ARG COMMIT
+ARG BUILD_DATE
+ARG PROJECT=github.com/falcosecurity/falcoctl
 
+RUN test -n "$RELEASE" || ( echo "The RELEASE argument is unset. Aborting" && false )
+RUN test -n "$COMMIT" || ( echo "The COMMIT argument is unset. Aborting" && false )
+RUN test -n "$BUILD_DATE" || ( echo "The BUILD_DATE argument is unset. Aborting" && false )
 
 COPY go.mod ./go.mod
 COPY go.sum ./go.sum
 RUN  go mod download
 
 COPY . ./
-RUN CGO_ENABLED=0 GOOS=$(go env GOOS) GOARCH=$(go env GOARCH) go build -ldflags="-s -w" ./
 
+RUN CGO_ENABLED=0 \
+    GOOS=$(go env GOOS) \
+    GOARCH=$(go env GOARCH) \
+    go build -ldflags \
+    "-s \
+    -w \
+    -X '${PROJECT}/cmd/version.semVersion=${RELEASE}' \
+    -X '${PROJECT}/cmd/version.gitCommit=${COMMIT}' \
+    -X '${PROJECT}/cmd/version.buildDate=${BUILD_DATE}'" \
+    ./
+
+RUN echo ${RELEASE}
 
 FROM alpine:3.16.3
 
